package routers

import (
	"CRMsystemproject/controllers"
	beego "github.com/beego/beego/v2/server/web"
)

func init() {
	beego.SetStaticPath("/img", "static/img")
	beego.Router("/", &controllers.MainController{})
	beego.Router("/index", &controllers.IndexController{})
	beego.Router("/register", &controllers.RegisterController{}, "GET:Get")
	beego.Router("/register", &controllers.RegisterController{}, "POST:Post")
	beego.Router("/login", &controllers.LoginController{}, "GET:Get")
	beego.Router("/login", &controllers.LoginController{}, "POST:Post")
	beego.Router("/user_management", &controllers.UserController{})
	beego.Router("/addUsers", &controllers.UserController{}, "POST:AddUsers")
	beego.Router("/getall", &controllers.UserController{}, "GET:GetAll")
	//beego.Router("/findbyid/:userid", &controllers.UserController{}, "get:FindById")
	beego.Router("/searchUser", &controllers.UserController{}, "POST:SearchUser")
	beego.Router("/deleteuser/:userid", &controllers.UserController{}, "DELETE:DeleteUser")
	beego.Router("/updateUser", &controllers.UserController{}, "PUT:UpdateUser")
	beego.Router("/getuser/:userid", &controllers.UserController{}, "GET:GetUserInfo")
	//beego.Router("/page", &controllers.UserController{}, "POST:ShowUserByPage")
	beego.Router("/pages", &controllers.UserController{}, "POST:ShowList")
	beego.Router("/", &controllers.CustomerController{})
	beego.Router("/customer_management", &controllers.CustomerController{})
	beego.Router("/customer_management/getall", &controllers.CustomerController{}, "GET:GetAll")
	beego.Router("/addcustomer", &controllers.CustomerController{}, "POST:AddCustomer")
	beego.Router("/customer_management/getCustomer/:customerId", &controllers.CustomerController{}, "GET:GetCustomer")
	beego.Router("/updateCustomer", &controllers.CustomerController{}, "PUT:UpdateCustomer")
	beego.Router("/customer_management/deleteCustomer/:customerid", &controllers.CustomerController{}, "delete:DeleteCustomer")
	beego.Router("/customer_management/searchCustomer", &controllers.CustomerController{}, "POST:SearchCustomer")
	beego.Router("/ShowCustomerByPage", &controllers.CustomerController{}, "post:ShowCustomerByPage")
	beego.Router("/ShowCustomerList", &controllers.CustomerController{}, "POST:ShowCustomerList")
	beego.Router("/order_view", &controllers.OrdersController{})
	beego.Router("/getall", &controllers.OrdersController{}, "GET:GetAll")
	beego.Router("/SearchOrder", &controllers.OrdersController{}, "POST:SearchOrder")
	beego.Router("/churn_customer_management", &controllers.ChurnCustomerController{})
	beego.Router("/get_churn_customer", &controllers.ChurnCustomerController{}, "GET:GetAll")
	beego.Router("/SearchChurnCustomer", &controllers.ChurnCustomerController{}, "POST:SearchChurnCustomer")
	beego.Router("/service_management", &controllers.ServiceManagementController{})
	beego.Router("/get_services", &controllers.ServiceManagementController{}, "GET:GetAll")
	beego.Router("/service_management/getservice/:serviceid", &controllers.ServiceManagementController{}, "GET:GetService")
	beego.Router("/updateService", &controllers.ServiceManagementController{}, "PUT:UpdateService")
	beego.Router("/deleteService/:serviceid", &controllers.ServiceManagementController{}, "DELETE:DeleteService")
	beego.Router("/service_management/searchService", &controllers.ServiceManagementController{}, "POST:SearchService")
	beego.Router("/ShowServiceByPage", &controllers.ServiceManagementController{}, "POST:ShowServiceByPage")
	beego.Router("/ShowServiceList", &controllers.ServiceManagementController{}, "POST:ShowServiceList")
	beego.Router("/addCreateOrder", &controllers.ServiceManagementController{}, "POST:CreateOrder")
	beego.Router("/api/getContactDetails/:contactId", &controllers.CustomerController{}, "GET:GetContactDetails")
	beego.Router("/markCustomerAsLost", &controllers.CustomerController{}, "POST:MarkCustomerAsLost")

}
